Facebook:    fb://
Twitter:     twitter://
Instagram:   instagram://
Snapchat:    snapchat://
LinkedIn:    linkedin://
WhatsApp:    whatsapp://
Telegram:    tg://
Slack:       slack://
Amazon:      amazon://
eBay:        ebay://
Etsy:        etsy://
Airbnb:      airbnb://
Uber:        uber://
Lyft:        lyft://
Spotify:     spotify://
Apple Music: music://
YouTube:     youtube://
Google Maps: comgooglemaps://
Chrome:      googlechrome://
Calendar:    calshow://
Pinterest:   pinterest://
TikTok:      tiktok://
Reddit:      reddit://
Gmail:       googlegmail://
Messenger:   fb-messenger://
Venmo:       venmo://
PayPal:      paypal://
Waze:        waze://
Yelp:        yelp://
Mail:        mailto://
Phone:       tel://
FaceTime:    facetime://
